### ISSUE TITLE
Post in Timeline was Unexpectedly Hided

### ISSUE THREAD

**Issue by Blacktea0** [hi2ma-bu4/X_impression_hide#2]
![2024-10-06_21-22-38](https://github.com/user-attachments/assets/d48197e5-f6b1-4ddd-933c-7c6b773b6326)
Post in timeline was unexpectedly hided. Effect scope should limit to replies only, I think.

**Comment by hi2ma-bu4** [comment]
Thank you.
First, I would like to inform you that this text uses Google Translate.

The phenomenon that posts on the home page are hidden occurs when you open and close posts quickly. This occurs because it is determined by the URL.
The following is a temporary solution.

If you are using tampermonkey, click the extension icon in the upper right corner of the screen on the twitter(X) page.

Click `設定を開く(S)` under (`Twitter(旧:𝕏)のインプレッション小遣い稼ぎ野郎どもをdisplay:none;するやつ` or `Hide the Twitter (formerly: 𝕏) impression-earning scammers with "display:none;"`)

If you want to change the language from Japanese to English, change the `言語` at the bottom of the menu that appears.

Next, set `Processing wait time (in milliseconds) for page update detection` in `Advanced settings` to a small integer.

This should reduce the chance of malfunctions on the home screen.

If you make the number smaller, processing may become heavier.

Finally, click save and refresh the page.

Finally, to make it easier to see again

Japanese:
```
設定を開く(S) > 高度な設定 > ページ更新検知用処理待機時間(ms)
```
English:
```
設定を開く(S) > Advanced settings > Processing wait time (in milliseconds) for page update detection
```

If you find any posts that have been hidden by mistake, please send us the URL and we will take action.

I apologize if my explanation is difficult to understand.

---
以下日本語
---
ありがとう。
先にこの文章はgoogle翻訳を使用している事をお伝えします。

ホームの投稿が非表示になる現象は高速で投稿を開いたり閉じたりすると発生します。これはurlで判定している為に発生する現象です。
以下に一時的な対応策をお知らせします。

tampermonkeyを使用している場合、twitter(X)のページで画面右上の拡張機能アイコンをクリックして下さい。
日本語の場合(`Twitter(旧:𝕏)のインプレッション小遣い稼ぎ野郎どもをdisplay:none;するやつ`)
か、
英語の場合(`Hide the Twitter (formerly: 𝕏) impression-earning scammers with "display:none;"`)
の下にある`設定を開く(S)`をクリックして下さい

言語を日本語から英語にする場合は表示されたメニューの一番下の`言語`を変更して下さい。

次に`高度な設定`(`Advanced settings`)の`ページ更新検知用処理待機時間(ms)`(`Processing wait time (in milliseconds) for page update detection`)を少ない整数に設定して下さい。
これでホームで誤動作をする確率が減少するはずです。
数値を小さくすると処理が重くなる可能性があります。
最後にsaveをクリックしてページを更新して下さい。

最後にもう一度見やすく
日本語:
```
設定を開く(S) > 高度な設定 > ページ更新検知用処理待機時間(ms)
```
英語:
```
設定を開く(S) > Advanced settings > Processing wait time (in milliseconds) for page update detection
```

誤って非表示にされた投稿があればurlを送って頂ければ対処いたします。

説明がわかりにくかったらお詫び申し上げます。

**Comment by Blacktea0** [comment]
ご丁寧にありがとうございます！助かります

**Comment by Blacktea0** [comment]
Aside from the timeline, I also noticed that when viewing tweets under a specific account, the retweeted tweets by the account holder are mistakenly blocked. I tried refreshing and adjusting the parameters, but the issue couldn't be resolved.

タイムライン以外にも、特定のアカウントのツイートを確認している際に、ツイート主がリツイートしたツイートも誤ってブロックされることに気付きました。リフレッシュやパラメータの調整を試しましたが、問題は解決しませんでした…

![image](https://github.com/user-attachments/assets/aff02327-6a8c-4e7e-be52-12115a98fff4)。

URL: https://x.com/reoenl

**Comment by hi2ma-bu4** [comment]
Thank you for reporting this issue.
We have confirmed that the issue can be reproduced, and will fix it before the next update.
Please feel free to let us know if you have any other issues.

---

ご報告ありがとうございます。
再現性を確認したので、次のアップデートまでに修正しておきます。
他の問題などもあればご気軽に相談して下さい。

**Comment by hi2ma-bu4** [comment]
Updating to v1.13.11 should fix the issue.
Please check.

---
v1.13.11 にアップデートすると問題が解決するはずです。
ご確認お願い致します。

**Comment by hi2ma-bu4** [comment]
返答が無いので解決と見なしてclose
